/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package autonoma.demoatrapacomida.gui;

import autonoma.demoatrapacomida.elements.VideoJuego;
import javax.swing.ImageIcon;

/**
 *
 * @author USUARIO
 */
public class VentanaInformacion extends javax.swing.JDialog {
    private VideoJuego juego;

    /**
     * Creates new form VentanaInformacion
     */
    public VentanaInformacion(java.awt.Frame parent, boolean modal,VideoJuego juego) {
         super(parent, modal);
        this.juego = juego;
        setTitle("Atrapa Comida");
        setSize(800, 800);
        setLocationRelativeTo(null);
        setResizable(false);

        
        this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/demoatrapacomida/images/Logo.jpeg")).getImage());

       
        ImageIcon fondo = new ImageIcon(getClass().getResource("/autonoma/demoatrapacomida/images/FondoInformacion.jpeg"));
        javax.swing.JPanel panelFondo = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                g.drawImage(fondo.getImage(), 0, 0, getWidth(), getHeight(), this);
            }
        };
        panelFondo.setLayout(null);

        
        javax.swing.JButton btnIniciar = new javax.swing.JButton("Iniciar juego");
        btnIniciar.setBounds(300, 600, 200, 40);
        btnIniciar.addActionListener(e -> {
          
            dispose();
        });

      
        javax.swing.JButton btnReiniciar = new javax.swing.JButton("Reiniciar juego");
        btnReiniciar.setBounds(300, 650, 200, 40);
        btnReiniciar.addActionListener(e -> {
         
          
        });

        panelFondo.add(btnIniciar);
        panelFondo.add(btnReiniciar);
        setContentPane(panelFondo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
