/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package autonoma.demoatrapacomida.gui;

import autonoma.demoatrapacomida.elements.VideoJuego;
import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author USUARIO
 */
public class VentanaInformacion extends javax.swing.JDialog {
    private VideoJuego juego;
    private JLabel labelNombre;
    private JLabel labelPuntaje;

    public VentanaInformacion(Frame parent, boolean modal, VideoJuego juego) {
            super(parent, modal);
            this.juego = juego;
            initComponents();
            setTitle("Atrapa Comida");
            setSize(800, 800);
            setLocationRelativeTo(null);
            setResizable(false);
            setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

            setLayout(null); 

            this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/demoatrapacomida/images/Logo.jpeg")).getImage());
            // Fondo
            JLabel fondo = new JLabel(new ImageIcon(getClass().getResource("/autonoma/demoatrapacomida/images/FondoInformacion.jpeg")));
            fondo.setBounds(0, 0, 800, 800);
            setContentPane(fondo);
            fondo.setLayout(null);

            // Fuente estilo videojuego más suave
            Font fuenteJuego = new Font("Monospaced", Font.BOLD, 24);
            Color colorLetra = new Color(127, 219, 255); 
            Color colorBorde = new Color(0, 51, 102, 180); 
            Border borde = BorderFactory.createLineBorder(colorBorde, 2);

            // Mostrar nombre del jugador
            String nombre = juego.getCampo().getJugador().getNombre();
            labelNombre = new JLabel("Jugador: " + nombre);
            labelNombre.setBounds(50, 30, 300, 40);
            labelNombre.setFont(fuenteJuego);
            labelNombre.setForeground(colorLetra);
            labelNombre.setBorder(borde);
            fondo.add(labelNombre);

            // Mostrar puntaje
            labelPuntaje = new JLabel("Puntaje: " + juego.getCampo().getJugador().getPuntaje().getPuntajeActual());
            labelPuntaje.setBounds(50, 80, 300, 40);
            labelPuntaje.setFont(fuenteJuego);
            labelPuntaje.setForeground(colorLetra);
            labelPuntaje.setBorder(borde);
            fondo.add(labelPuntaje);

            // Centrado de botones
            int botonAncho = 180;
            int xCentro = (800 - botonAncho) / 2;

             // Botón Iniciar Juego
             JButton btnIniciar = new JButton("Iniciar Juego");
             btnIniciar.setBounds(xCentro, 220, botonAncho, 35);
             estiloBoton(btnIniciar);
             btnIniciar.addActionListener(e -> {
                 new VentanaJuego((Frame) getParent(), true, juego).setVisible(true);
                 dispose();
             });
             fondo.add(btnIniciar);

             // Botón Reiniciar Juego
             JButton btnReiniciar = new JButton("Reiniciar Juego");
             btnReiniciar.setBounds(xCentro, 270, botonAncho, 35);
             estiloBoton(btnReiniciar);
             btnReiniciar.addActionListener(e -> {
                 juego.reinicarJuego();
                 labelPuntaje.setText("Puntaje: " + juego.getCampo().getJugador().getPuntaje().getPuntajeActual());
                 JOptionPane.showMessageDialog(this, "El juego ha sido reiniciado.");
             });
             fondo.add(btnReiniciar);
            addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                int confirm = JOptionPane.showConfirmDialog(null,
                "¿Estás seguro de que deseas salir del juego?",
                "Confirmar salida",
                JOptionPane.YES_NO_OPTION
            );
                if (confirm == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }  
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void estiloBoton(JButton boton) {
        boton.setForeground(Color.WHITE);
        boton.setFont(new Font("Arial", Font.BOLD, 16));
        boton.setOpaque(false);
        boton.setContentAreaFilled(false);
        boton.setBorderPainted(true);
        boton.setFocusPainted(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
