/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package autonoma.demoatrapacomida.gui;

import autonoma.demoatrapacomida.elements.VideoJuego;
import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class VentanaInformacion extends javax.swing.JDialog {
    private VideoJuego juego;
    private JLabel labelNombre;
    private JLabel labelPuntaje;

    public VentanaInformacion(Frame parent, boolean modal, VideoJuego juego) {
            super(parent, modal);
            this.juego = juego;
            initComponents();
            setTitle("Atrapa Comida");
            setSize(800, 800);
            setLocationRelativeTo(null);
            setResizable(false);

            setLayout(null); 

            this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/demoatrapacomida/images/Logo.jpeg")).getImage());
            // Fondo
            JLabel fondo = new JLabel(new ImageIcon(getClass().getResource("/autonoma/demoatrapacomida/images/FondoInformacion.jpeg")));
            fondo.setBounds(0, 0, 800, 800);
            setContentPane(fondo);
            fondo.setLayout(null);

            // Mostrar nombre del jugador
            String nombre = juego.getCampo().getJugador().getNombre();
            labelNombre = new JLabel("Jugador: " + nombre);
            labelNombre.setBounds(50, 30, 300, 30);
            labelNombre.setFont(new Font("Arial", Font.BOLD, 20));
            labelNombre.setForeground(Color.WHITE);
            fondo.add(labelNombre);

            // Mostrar puntaje
            labelPuntaje = new JLabel("Puntaje: " + juego.getCampo().getJugador().getPuntaje());
            labelPuntaje.setBounds(50, 70, 300, 30);
            labelPuntaje.setFont(new Font("Arial", Font.BOLD, 20));
            labelPuntaje.setForeground(Color.WHITE);
            fondo.add(labelPuntaje);

            // Botón Iniciar Juego
            JButton btnIniciar = new JButton("Iniciar Juego");
            btnIniciar.setBounds(200, 220, 180, 35);
            btnIniciar.addActionListener(e -> {
                new VentanaJuego((Frame) getParent(), true, juego).setVisible(true);
                dispose();
            });
            fondo.add(btnIniciar);

            // Botón Reiniciar Juego
            JButton btnReiniciar = new JButton("Reiniciar Juego");
            btnReiniciar.setBounds(200, 270, 180, 35);
            btnReiniciar.addActionListener(e -> {
                
                JOptionPane.showMessageDialog(this, "El juego ha sido reiniciado.");
                dispose();
            });
            fondo.add(btnReiniciar);
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
